#
# The Alluxio Open Foundation licenses this work under the Apache License, version 2.0
# (the "License"). You may not use this work except in compliance with the License, which is
# available at www.apache.org/licenses/LICENSE-2.0
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied, as more fully set forth in the License.
#
# See the NOTICE file distributed with this work for information regarding copyright ownership.
#

{{- if not (eq .Values.worker.enabled false) -}}

{{ $workerCount := int .Values.worker.count }}
{{- $release := .Release }}
{{- $name := include "alluxio.name" . }}
{{- $fullName := include "alluxio.fullname" . }}
{{- $chart := include "alluxio.chart" . }}
{{- range $i := until $workerCount }}
  {{- $workerName := printf "master-%v" $i }}
  {{- $workerJavaOpts := printf " -Dalluxio.worker.hostname=%v-%v " $fullName $workerName }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-{{ $workerName }}
  labels:
    app: {{ $name }}
    chart: {{ $chart }}
    release: {{ $release.Name }}
    heritage: {{ $release.Service }}
    role: alluxio-worker
spec:
  ports:
    - port: 29999
      name: rpc
    - port: 30000
      name: web
    - port: 30001
      name: job-rpc
    - port: 30003
      name: job-web
    - port: 30002
      name: job-data
  clusterIP: None
  selector:
    role: alluxio-worker
    app: {{ $name }}
    release: {{ $release.Name }}
    statefulset.kubernetes.io/pod-name: {{ $fullName }}-{{ $workerName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-{{ $workerName }}-external
  labels:
    app: {{ $name }}
    chart: {{ $chart }}
    release: {{ $release.Name }}
    heritage: {{ $release.Service }}
    role: alluxio-worker
spec:
  type: NodePort
  ports:
    - port: 29999
      name: rpc
    - port: 30000
      name: web
    - port: 30001
      name: job-rpc
    - port: 30002
      name: job-data
    - port: 30003
      name: job-web
  selector:
    role: alluxio-worker
    app: {{ $name }}
    release: {{ $release.Name }}
    statefulset.kubernetes.io/pod-name: {{ $fullName }}-{{ $workerName }}
{{- end }}
{{- end }}
